### PR TITLE
Gd patches

### PR DESCRIPTION
**Pull request by pbenas**

### CODE REVIEW

**Comment by pbenas** [comment]
The diff of ci-infra generated XMLs is quite large, but mainly added attributes. No idea how to check if it would work with our version of Jenkins. We might try some of the jobs on ci-dev, but not all of them. 
https://gist.github.com/pbenas/d6b95dab5e0917d1c95c

**Comment by hrubi** [comment]
Several deprecation warnings, please create a followup to fix them (eg. prepare a PR to ci-infra):

```
tag '!include-raw' is deprecated, switch to using '!include-raw:'
Your pollscm usage is deprecated, please use the syntax described in the documentation instead
```

**Comment by hrubi** [comment]
Check that the following works with our version of Jenkins - verification that Jenkins does not complain about unknown option should be ok:
- `<hudson.tasks.junit.JUnitResultArchiver><healthScaleFactor>`
- `<buildStep class="hudson.plugins.copyartifact.CopyArtifact"><doNotFingerprintArtifacts>`
- `<hudson.plugins.buildblocker.BuildBlockerProperty><blockLevel>`, `<hudson.plugins.buildblocker.BuildBlockerProperty><scanQueueFor>`
- `<hudson.plugins.emailext.ExtendedEmailPublisher><disabled>false</disabled>`
- `<hudson.plugins.sonar.SonarPublisher><rootPom>`, `<hudson.plugins.sonar.SonarPublisher><usePrivateRepository>` `<hudson.plugins.sonar.SonarPublisher><settings class="jenkins.mvn.DefaultSettingsProvider"/>`, `<hudson.plugins.sonar.SonarPublisher><globalSettings class="jenkins.mvn.DefaultGlobalSettingsProvider"/>`

Other than changed attributes:
- check that the `TEST` variable used in RAT tests works when tests are separated by newline instead of a space. Sample job: hotfix-ROLAP-pg-REST

**Comment by pbenas** [comment]
Closing because of the switch to GD fork which happened meanwhile. Will open a new PR against the GD fork after verifying what Hrubi asked for.

**Pull request closed without merging**
